#!/usr/bin/env python3
"""Generate rtl/gen/ from the tables in this directory, and refuse to if they
are wrong.

    python3 tools/ucode/assemble.py            # regenerate
    python3 tools/ucode/assemble.py --check    # fail if what is checked in is stale

The generated files are committed, so a build needs no Python. `make ucode-check`
is the first thing `make check` runs, so they cannot drift from their source.

The generator is also the design-rule checker. Some properties cannot be stated in
RTL -- that no two checkpointed registers share a bit of the fault frame, that the
short frame carries no private state, that every frame is exactly as long as the
manual says -- so they are stated here and fail the build instead.

As of M4 this emits the frame package. The microword, the decoders and the
microcode store arrive in M5.
"""

import argparse
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
GEN = os.path.join(ROOT, 'rtl', 'gen')
sys.path.insert(0, HERE)

import frames                                                   # noqa: E402
import isa                                                      # noqa: E402
import program                                                  # noqa: E402

BANNER = """// RD68021 - SystemVerilog MC68020
//
// GENERATED by tools/ucode/assemble.py from tools/ucode/frames.py. Do not edit:
// `make ucode-check` compares this file against its source and fails the build if
// they have drifted.
//
"""


def frame_pkg():
    out = [BANNER]
    out.append("""// The six exception stack frames -- UM Table 6-5 -- and the offsets this design
// keeps its own state at inside the long one.
//
// One wrong offset here is a silent demand-paging failure: the frame would be
// written correctly enough to pass its own format check and read back one word
// out. tools/ucode/frames.py is the single place any of these numbers exists.

`ifndef RD68021_FRAME_PKG_SV
`define RD68021_FRAME_PKG_SV

package rd68021_frame_pkg;

  // ==========================================================================
  // Frame sizes, in bytes, as the stack pointer must be adjusted by
  // ==========================================================================""")
    for fmt in sorted(frames.FRAMES):
        f = frames.FRAMES[fmt]
        out.append('  localparam int FRAME_%X_BYTES = %d;   // %s, %d words'
                   % (fmt, 2 * f['words'], f['name'], f['words']))

    out.append("""
  // ==========================================================================
  // Architecturally named fields -- UM Table 6-5
  //
  // OFF is the byte offset from the stack pointer; a field present in more than
  // one frame is at the same offset in each, which is what makes one set of
  // constants right for all of them.
  // ==========================================================================""")
    seen = {}
    for fmt in sorted(frames.FRAMES):
        for off, n, field in frames.FRAMES[fmt]['slots']:
            if field in ('internal', 'version'):
                continue
            if field in seen:
                if seen[field] != (off, n):
                    raise SystemExit('assemble: field %r is at +$%02X in one frame '
                                     'and +$%02X in another -- the generator assumes '
                                     'it is not' % (field, seen[field][0], off))
                continue
            seen[field] = (off, n)
            out.append('  localparam int OFF_%-13s = \'h%02X;   // %d word%s, %s'
                       % (field.upper(), off, n, '' if n == 1 else 's',
                          frames.ARCH_FIELDS[field]))

    out.append("""
  // ==========================================================================
  // The version number -- UM 6.1.12
  //
  // "The version number is located in the most significant nibble (bits 15-12)
  // of the word at location SP + $36 in the long stack frame." RTE compares it
  // with its own and takes a format error if they differ, which is the contract
  // that makes this design's private encoding of the internal words legitimate.
  // It is also why the SHORT frame, which has no version field, carries none of
  // them. See doc/manual-contradictions.md for why the offset is $36.
  // ==========================================================================""")
    out.append('  localparam int         OFF_VERSION  = \'h%02X;' % frames.VERSION_OFFSET)
    out.append('  localparam int         VERSION_HI   = %d;' % frames.VERSION_HI)
    out.append('  localparam int         VERSION_LO   = %d;' % frames.VERSION_LO)
    out.append('  localparam logic [3:0] FRAME_VERSION = 4\'h%X;' % frames.VERSION)

    have, use, spare = frames.budget()
    out.append("""
  // ==========================================================================
  // This design's own state, in the long frame's internal words
  //
  // %d bits available, %d used, %d words spare. Recompute this whenever
  // something is added: doc/checkpoint.md carries the same table, printed from
  // the same source.
  // ==========================================================================""" % (have, use, len(spare)))
    for off, hi, lo, name, bits, what in frames.INTERNAL:
        out.append('  localparam int OFF_%-11s = \'h%02X;   // %2d bits, %s'
                   % ('I_' + name.upper(), off, bits, what))
        out.append('  localparam int %-15s = %d;'
                   % ('I_' + name.upper() + '_HI', hi))
        out.append('  localparam int %-15s = %d;'
                   % ('I_' + name.upper() + '_LO', lo))

    out.append("""
endpackage

`endif""")
    return '\n'.join(out) + '\n'


def doc_tables():
    """The tables doc/checkpoint.md carries, printed from the same source."""
    out = []
    out.append('### The frames\n')
    out.append('| Format | Words | Name | Layout |')
    out.append('|---|--:|---|---|')
    for fmt in sorted(frames.FRAMES):
        f = frames.FRAMES[fmt]
        bits = []
        for off, n, field in f['slots']:
            label = field if field != 'internal' else 'internal'
            bits.append('`+$%02X` %s%s' % (off, label,
                                           '' if n == 1 else ' ×%d' % n))
        out.append('| `$%X` | %d | %s | %s |'
                   % (fmt, f['words'], f['name'], ', '.join(bits)))

    out.append('\n### The private words of the long frame\n')
    out.append('| Offset | Bits | Register | What |')
    out.append('|---|---|---|---|')
    for off, hi, lo, name, bits, what in frames.INTERNAL:
        r = '%d' % hi if hi == lo else '%d:%d' % (hi, lo)
        out.append('| `+$%02X` | %s | `%s` | %s |' % (off, r, name, what))
    have, use, spare = frames.budget()
    out.append('\n**%d bits available, %d used, %d words spare** (%s).'
               % (have, use, len(spare),
                  ', '.join('`+$%02X`' % w for w in spare)))

    out.append('\n### The frozen set\n')
    out.append('| Unit | Register | Bits | Lands in | |')
    out.append('|---|---|--:|---|---|')
    for unit, reg, bits, slot, note in frames.CHECKPOINT:
        out.append('| `%s` | `%s` | %d | `%s` | %s |' % (unit, reg, bits, slot, note))

    out.append('\n### Not checkpointed, and why\n')
    out.append('| | |')
    out.append('|---|---|')
    for what, why in frames.NOT_CHECKPOINTED:
        out.append('| %s | %s |' % (what, why))
    return '\n'.join(out) + '\n'


# --------------------------------------------------------------------------
# The microcode store
# --------------------------------------------------------------------------
def assemble_words():
    """Every microword as an integer, with `next` resolved.

    Fall-through is the default: a microword whose `seq` is NEXT and which names
    no successor runs the one after it. An unset field can therefore never mean
    micro-address zero by accident.
    """
    lay, width = isa.layout()
    out = []
    for i, (fields, _comment) in enumerate(program.WORDS):
        word = 0
        for name, (lsb, w) in lay.items():
            enc = isa.FIELDS[name][1]
            default = isa.FIELDS[name][2]
            v = fields.get(name, default)
            if name == 'next':
                if name in fields:
                    v = program.entry(fields['next']) if isinstance(v, str) else v
                else:
                    v = i + 1        # fall through
            elif enc is not None:
                if v not in enc:
                    raise SystemExit('assemble: microword %d: %r is not a value of '
                                     'field %r' % (i, v, name))
                v = enc[v]
            if v < 0 or v >= (1 << w):
                raise SystemExit('assemble: microword %d: field %r value %d does '
                                 'not fit in %d bits' % (i, name, v, w))
            word |= v << lsb
        out.append(word)
    return out, width


# --------------------------------------------------------------------------
# The opcode decoder
#
# Written as an ordered list -- first match wins -- and emitted as DISJOINT
# patterns, because Quartus builds an ordered casez as a priority chain and does
# not flatten it. On the MC68010 project that cost 1401 patterns 498 logic levels
# and 4.67 MHz where Vivado and yosys flattened the same source.
#
# The order is resolved once, here, and the two tables are then proved to agree
# over all 65536 opcodes.
# --------------------------------------------------------------------------
def cube_minus(a, b):
    """The cubes covering a but not b."""
    n = len(a)
    for i in range(n):
        if a[i] != '-' and b[i] != '-' and a[i] != b[i]:
            return [a]                      # disjoint already
    out = []
    cur = list(a)
    for i in range(n):
        if b[i] != '-' and a[i] == '-':
            piece = list(cur)
            piece[i] = '1' if b[i] == '0' else '0'
            out.append(''.join(piece))
            cur[i] = b[i]
    return out


def make_disjoint(pats):
    out = []
    for i, (p, t, m) in enumerate(pats):
        cubes = [p]
        for q, _, _ in pats[:i]:
            nxt = []
            for c in cubes:
                nxt.extend(cube_minus(c, q))
            cubes = nxt
        if not cubes:
            raise SystemExit('assemble: opcode pattern %s (%s) is completely '
                             'shadowed by an earlier one' % (p, m))
        for c in cubes:
            out.append((c, t, m))
    return out


def _match(pattern, op):
    n = len(pattern)
    for i, c in enumerate(pattern):
        if c == '-':
            continue
        if ((op >> (n - 1 - i)) & 1) != int(c):
            return False
    return True


def check_disjoint(ordered, disjoint, width=16):
    """The two tables agree over every input, and no two disjoint cubes overlap."""
    bad = []
    for op in range(1 << width):
        a = None
        for p, t, _ in ordered:
            if _match(p, op):
                a = t
                break
        hits = [t for p, t, _ in disjoint if _match(p, op)]
        if len(hits) > 1:
            bad.append('input $%05X matches %d disjoint patterns' % (op, len(hits)))
            if len(bad) > 4:
                break
        b = hits[0] if hits else None
        if a != b:
            bad.append('input $%05X: ordered says %r, disjoint says %r'
                       % (op, a, b))
            if len(bad) > 4:
                break
    return bad


def ucode_pkg():
    lay, width = isa.layout()
    out = [BANNER]
    out.append("""// The microword: every field position and every encoding the microcode can use,
// so that the RTL and the microcode cannot drift apart. tools/ucode/isa.py is the
// only place any of this is decided.

`ifndef RD68021_UCODE_PKG_SV
`define RD68021_UCODE_PKG_SV

package rd68021_ucode_pkg;
""")
    out.append('  localparam int UW    = %d;   // microword width' % width)
    out.append('  localparam int UADDR = %d;   // micro-address width' % isa.UADDR_BITS)
    out.append('')
    for name, (lsb, w) in lay.items():
        out.append('  localparam int U_%s_LSB = %d;' % (name.upper(), lsb))
        out.append('  localparam int U_%s_W   = %d;' % (name.upper(), w))
    out.append('')
    for name, (w, e, _d) in isa.FIELDS.items():
        if e is None:
            continue
        for k, v in e.items():
            out.append("  localparam logic [%d:0] U_%s_%s = %d'd%d;"
                       % (w - 1, name.upper(), k, w, v))
        out.append('')
    out.append('  // Named entry points.')
    # The entry points hardware reaches without the microcode asking: reset,
    # the decoder's fall-through, and the trace exception, which the sequencer
    # puts in front of the decode arm at every instruction boundary.
    for lbl in ('reset', 'illegal', 'exc_trace', 'exc_irq',
                'exc_fault_long', 'exc_line_f',
                'exc_cp_irq'):
        out.append('  localparam logic [UADDR-1:0] ENTRY_%s = %d\'d%d;'
                   % (lbl.upper().replace('EXC_', ''),
                      isa.UADDR_BITS,
                      program.entry(lbl)))
    out.append("""
endpackage

`endif""")
    return '\n'.join(out) + '\n'


def ucode_rom():
    words, width = assemble_words()
    out = [BANNER]
    out.append("""// The microcode store.
//
// Read at `addr`, which the sequencer drives with the NEXT micro-address rather
// than the current one, and registered: the same word arrives at the same time as
// the micro-address it belongs to, with no clock lost and with a memory instead of
// logic.
//
// The read register has NO reset, and it is the one register in the design that
// does not -- tools/reset_audit.py names it. A memory's output register cannot
// carry a reset value into a block RAM on every part: Vivado absorbs one, and
// Quartus, given one, builds the whole store out of logic instead (measured on a
// Cyclone V: 8,797 ALMs and two memory blocks, where the store alone is 150
// kilobits). An ASIC ROM macro has no reset on its output either.
//
// It is reset-EQUIVALENT instead. While reset is asserted the address is forced
// to the reset entry point, so the register holds the reset word from the first
// clock edge inside reset -- and the clock runs during reset by requirement: UM
// 5.8 has RESET asserted for at least 520 clocks at power-up. The sequencer's
// micro-PC comes out of reset at the same entry point, so the two agree on the
// first edge after reset whichever side of it reset is released.

// The port widths are literals rather than rd68021_ucode_pkg::UADDR-1 and UW-1:
// iverilog rejects a package-scoped constant in a port declaration with a bare
// "syntax error" and no hint as to which token it minded. The generator knows
// both numbers, so it writes them out. doc/coding-standard.md.
module rd68021_ucode_rom (
    input  logic          clk,
    input  logic          rst_n,
    input  logic [%d:0]   addr,
    output logic [%d:0]   uw
);

  logic [%d:0] a;
  assign a = rst_n ? addr : %d'd%d;

  // Say which memory and stop it being a choice: Vivado's ROM inference in its
  // own synthesis report is preliminary and timing optimisation may reverse it
  // with no message. The attribute is on a register DECLARATION, which is where
  // both tools look for it -- on the always block Quartus ignores it with
  // Warning 10335 -- and Quartus picks the block type for the family itself.
  (* rom_style = "block" *)
  logic [%d:0] rom_q;
  assign uw = rom_q;

  always_ff @(posedge clk) begin
      case (a)""" % (isa.UADDR_BITS - 1, width - 1,
                            isa.UADDR_BITS - 1, isa.UADDR_BITS,
                            program.entry('reset'), width - 1))
    for i, w in enumerate(words):
        _f, comment = program.WORDS[i]
        out.append("        %d'd%-5d: rom_q <= %d'h%0*X;%s"
                   % (isa.UADDR_BITS, i, width, (width + 3) // 4, w,
                      ('   // ' + comment) if comment else ''))
    out.append("""        default:      rom_q <= %d'h%0*X;   // the illegal entry
      endcase
  end

endmodule""" % (width, (width + 3) // 4, words[program.entry('illegal')]))
    return '\n'.join(out) + '\n'


def decode_rom():
    ordered = program.PATTERNS
    disjoint = make_disjoint(ordered)
    bad = check_disjoint(ordered, disjoint)
    if bad:
        raise SystemExit('assemble: the disjoint decode table does not agree with '
                         'the ordered one:\n  ' + '\n  '.join(bad))
    out = [BANNER]
    out.append("""// The opcode decoder: an instruction word in, a micro-address out.
//
// The patterns in tools/ucode/program.py are ORDERED -- first match wins -- and
// are emitted here as DISJOINT ones, because Quartus builds an ordered casez as a
// priority chain and does not flatten it. assemble.py resolves the order once, in
// Python, and proves the two tables agree over all 65536 opcodes.
//
// %d ordered patterns became %d disjoint ones.

module rd68021_decode_rom (
    input  logic [15:0]                         ir,
    output logic [%d:0] entry,
    output logic                                illegal
);

  always_comb begin
    illegal = 1'b0;
    casez (ir)""" % (len(ordered), len(disjoint), isa.UADDR_BITS - 1))
    for p, t, m in disjoint:
        out.append("      16'b%s: entry = %d'd%d;   // %s"
                   % (p.replace('-', '?'), isa.UADDR_BITS, program.entry(t), m))
    out.append("""      default: begin
        entry   = rd68021_ucode_pkg::ENTRY_ILLEGAL;
        illegal = 1'b1;
      end
    endcase
  end

endmodule""")
    return '\n'.join(out) + '\n'


def eadec_rom():
    ordered = program.EAPATTERNS
    disjoint = make_disjoint(ordered)
    bad = check_disjoint(ordered, disjoint, width=17)
    if bad:
        raise SystemExit('assemble: the disjoint extension-word table does not '
                         'agree with the ordered one:\n  ' + '\n  '.join(bad))
    out = [BANNER]
    out.append("""// The extension-word decoder: the shape of an effective address in, a
// micro-address out.
//
// A full extension word decides how many words of base and outer displacement
// follow and whether a memory indirection happens -- five bus-steering decisions
// taken from a word that has only just been read. Branching on them microword by
// microword would put all five into the bus request's fan-in, which is the one
// thing the microcode may not do. Resolving them once, in hardware, into a
// micro-address puts none of them there. It is the opcode decoder's trick on a
// different word.
//
// The seventeenth bit is not part of the extension word. It says whether the
// base of the address is the program counter or an address register, which is in
// the OPCODE -- so the microword supplies it.
//
// %d ordered patterns became %d disjoint ones.

module rd68021_eadec_rom (
    input  logic        pc_base,
    input  logic [15:0] xw,
    output logic [UA:0] entry,
    output logic        reserved
);

  always_comb begin
    reserved = 1'b0;
    casez ({pc_base, xw})
""" % (len(ordered), len(disjoint)))
    out[-1] = out[-1].replace('[UA:0]', '[%d:0]' % (isa.UADDR_BITS - 1))
    for p, t, m in disjoint:
        out.append("      17'b%s: entry = %d'd%d;   // %s"
                   % (p.replace('-', '?'), isa.UADDR_BITS, program.entry(t), m))
    out.append("""      default: begin
        entry    = rd68021_ucode_pkg::ENTRY_ILLEGAL;
        reserved = 1'b1;
      end
    endcase
  end

endmodule""")
    return '\n'.join(out) + '\n'


def cpdec_rom():
    """The response primitive decoder: a coprocessor's request in, a
    micro-address out -- UM 7.4.

    The same trick as the extension-word decoder. A primitive read from the
    response CIR decides which interface register is read next, which way an
    operand moves, whether the effective address is evaluated, and whether the
    request is refused outright as a protocol violation (UM table 7-6); resolving
    that once, in hardware, keeps every one of those decisions out of the bus
    request's fan-in.
    """
    ordered = program.CPPATTERNS
    disjoint = make_disjoint(ordered)
    bad = check_disjoint(ordered, disjoint, width=17)
    if bad:
        raise SystemExit('assemble: the disjoint primitive table does not agree '
                         'with the ordered one:\n  ' + '\n  '.join(bad))
    out = [BANNER]
    out.append("""// The coprocessor response primitive decoder -- UM 7.4 and table 7-6.
//
// Seventeen bits in: the instruction's category (1 for a conditional one, whose
// dialogue allows less) and the sixteen-bit primitive read from the response
// CIR. A micro-address out. Every encoding the manual leaves undefined, and
// every one it forbids in a conditional instruction, lands on the protocol
// violation -- UM 7.5.2.1.
//
// %d ordered patterns became %d disjoint ones.

module rd68021_cpdec_rom (
    input  logic        cond_cat,
    input  logic [15:0] prim,
    output logic [%d:0] entry
);

  always_comb begin
    casez ({cond_cat, prim})
""" % (len(ordered), len(disjoint), isa.UADDR_BITS - 1))
    for p, t, m in disjoint:
        out.append("      17'b%s: entry = %d'd%d;   // %s"
                   % (p.replace('-', '?'), isa.UADDR_BITS, program.entry(t), m))
    out.append("""      default: entry = %d'd%d;   // undefined: a protocol violation
    endcase
  end

endmodule""" % (isa.UADDR_BITS, program.entry('cp_protocol')))
    return '\n'.join(out) + '\n'


def eamode_rom():
    """The addressing-mode decoder: six bits of stage D in, a micro-address out.

    The same trick as the opcode and extension-word decoders, one level down.
    Without it every instruction with an effective address needs one opcode
    pattern per addressing mode -- eighteen of them, times eighty instructions --
    and the decode table stops being something anyone can read.
    """
    ordered = program.MODEPATTERNS
    disjoint = make_disjoint(ordered)
    bad = check_disjoint(ordered, disjoint, width=6)
    if bad:
        raise SystemExit('assemble: the disjoint addressing-mode table does not '
                         'agree with the ordered one:\n  ' + '\n  '.join(bad))
    out = [BANNER]
    out.append("""// The addressing-mode decoder: the mode and register fields of the instruction
// word in, the micro-address of the routine that computes that address out.
//
// %d ordered patterns became %d disjoint ones.

module rd68021_eamode_rom (
    input  logic  [5:0] mr,
    output logic [%d:0] entry,
    output logic        illegal
);

  always_comb begin
    illegal = 1'b0;
    casez (mr)
""" % (len(ordered), len(disjoint), isa.UADDR_BITS - 1))
    for p, t, m in disjoint:
        out.append("      6'b%s: entry = %d'd%d;   // %s"
                   % (p.replace('-', '?'), isa.UADDR_BITS, program.entry(t), m))
    out.append("""      default: begin
        entry   = rd68021_ucode_pkg::ENTRY_ILLEGAL;
        illegal = 1'b1;
      end
    endcase
  end

endmodule""")
    return '\n'.join(out) + '\n'


def checkpoint_doc():
    """doc/checkpoint.md with its tables replaced by the generated ones.

    The document is written by hand and its three tables are not: they are the
    frozen set, and a copy of them that can drift is worse than no copy. It had
    drifted -- the instruction pipe's registers were renamed and the document
    still named the old ones -- so the span between the two headings is spliced
    in here and `make ucode-check` fails when it does not match.
    """
    path = os.path.join(ROOT, 'doc', 'checkpoint.md')
    doc = open(path).read()
    gen = doc_tables()
    first, last = '### The frames', '### Not checkpointed, and why'
    return doc[:doc.index(first)] + gen[gen.index(first):gen.index(last)] \
        + doc[doc.index(last):]


OUTPUTS = {
    os.path.join(GEN, 'rd68021_eamode_rom.sv'): eamode_rom,
    os.path.join(GEN, 'rd68021_frame_pkg.sv'): frame_pkg,
    os.path.join(GEN, 'rd68021_eadec_rom.sv'): eadec_rom,
    os.path.join(GEN, 'rd68021_cpdec_rom.sv'): cpdec_rom,
    os.path.join(GEN, 'rd68021_ucode_pkg.sv'): ucode_pkg,
    os.path.join(GEN, 'rd68021_ucode_rom.sv'): ucode_rom,
    os.path.join(GEN, 'rd68021_decode_rom.sv'): decode_rom,
    os.path.join(ROOT, 'build', 'checkpoint-tables.md'): doc_tables,
    os.path.join(ROOT, 'doc', 'checkpoint.md'): checkpoint_doc,
}


# --------------------------------------------------------------------------
# A condition may not read the register the same microword writes
#
# A condition is evaluated against the register as it STANDS. The microword's
# own write is a non-blocking assignment that lands on the edge the microword
# retires -- the same edge the condition steers -- so a microword that writes a
# register and branches on it branches on the value BEFORE it.
#
# RTE found it. `dst = XW, cond = FMT1` on one microword tested the format word
# of the frame the PREVIOUS RTE had unwound, so a throwaway frame fell through
# to the four-word test, failed it, and became a format error. Nothing else
# noticed, because the FMT2 and FMT0 tests sit on later microwords and read the
# register correctly.
#
# The same shape is deliberate for the conditions that read the ALU RESULT --
# RESNEG, GTZ, RESM1, CAS_EQ -- which exist precisely to test what the current
# microword computes, so they are not in this table.
# --------------------------------------------------------------------------
COND_READS = {
    'FMT0': 'XW', 'FMT1': 'XW', 'FMT2': 'XW', 'FMTA': 'XW', 'FMTB': 'XW', 'FMT9': 'XW',
    'XW10': 'XW', 'XW11': 'XW', 'XW15': 'XW',
    'EMPTY': 'T0', 'NOTEMPTY': 'T0',
    'MODBAD': 'T0', 'MODTYPE1': 'T0', 'MODOPT4': 'T0',
    'ASTAT_BAD': 'T2', 'ASTAT_STACK': 'T2', 'T3ZERO': 'T3',
    'USER': 'SR', 'MASTER': 'SR',
    'CPCA': 'CPRIM', 'CPPC': 'CPRIM', 'CPDR': 'CPRIM', 'CPB8': 'CPRIM',
    'CPPF': 'CPRIM', 'CPTF': 'CPRIM', 'CPEAOK': 'CPRIM', 'CPMEAOK': 'CPRIM',
    'CPLEN124': 'CPRIM',
    'T1GE4': 'T1', 'T1B1': 'T1', 'T1B0': 'T1', 'T1ZERO': 'T1',
    'FWNOTRDY': 'T0', 'FWEMPTY': 'T0', 'FWBAD': 'T0', 'FWLEN': 'T0',
    'CREGBAD': 'XW', 'IRQPEND': 'SR',
}

# ... and the ones that read the CONDITION CODES, which a microword writes
# through the `ccr` field rather than through `dst`. Same mistake, same clock,
# different field: CAS compared and branched on the Z it was itself setting, so
# it swapped on the PREVIOUS instruction's verdict.
#
# The conditions that read the ALU RESULT -- RESNEG, GTZ, RESM1, MDOVF -- are
# not here, for the reason they are not in the table above: testing what the
# current microword computes is what they exist for.
COND_READS_CCR = ('CC', 'NCC', 'ZSET', 'CSET', 'VSET')


def check_areg_size():
    """An address register written at less than a long word is a data move.

    PRM 2 sign-extends a word into an address register because the word is a
    VALUE -- MOVEA.W is the instruction that rule exists for. The address a
    postincrement or predecrement leaves behind is not a value: it is already
    thirty-two bits, and extending it at the operand size truncates it.

    The two look identical in a microword -- both write an address register --
    so the ones that carry an address say so, and this insists that any write
    at a size the microword does not fix at long is one of them. It was a latent
    bug for two milestones: every `(An)+` and `-(An)` step went through the
    sign-extending destination, and the only reason nothing failed is that the
    sweep's addresses all have the relevant bit clear.
    """
    bad = []
    for i, (f, c) in enumerate(program.WORDS):
        if f.get('dst') not in ('AREG', 'AREG_EA'):
            continue
        if f.get('szsel', 'FIXED') == 'FIXED' and f.get('size', 'LONG') == 'LONG':
            continue
        bad.append('microword %d writes an address register at a size that is '
                   'not fixed at long, so it must use the ADDR destination -- %s'
                   % (i, c))
    return bad


def check_restore_order():
    """RTE writes the pipe's program counter before any other pipe field.

    rd68021_ifu stops its autonomous refill from the first write of the program
    counter until the load that completes the restore -- the refill would
    otherwise push the handler's instruction stream into the stages being put
    back. So the program counter has to come first, and a write of stage D on
    its own, which is what BKPT does, is not the start of a restore.
    """
    bad = []
    pipe = ('STG_D', 'STG_C', 'STG_B', 'PC_D', 'FILL', 'PIPE_F')
    for entry in ('rte_fault_short', 'rte_fault_long'):
        i = program.LABELS[entry]
        while i < len(program.WORDS):
            f, c = program.WORDS[i]
            if f.get('dst') in pipe:
                if f['dst'] != 'PC_D':
                    bad.append('%s writes %s before the program counter, so the '
                               'pipe is not frozen while it is put back -- '
                               'microword %d, %s' % (entry, f['dst'], i, c))
                break
            i += 1
    return bad


def check_cond_dst():
    bad = []
    for i, (f, c) in enumerate(program.WORDS):
        # cnt = CLRLOW writes T0 as well, beside whatever `dst` writes; the two
        # on one microword would be two writes to one register.
        if f.get('cnt') == 'CLRLOW' and f.get('dst') == 'T0':
            bad.append('microword %d clears a bit of T0 and writes T0 -- %s'
                       % (i, c))
        if f.get('seq') != 'COND':
            continue
        reads = COND_READS.get(f.get('cond'))
        if reads is not None and (f.get('dst') == reads
                                  or (reads == 'T0' and f.get('cnt') == 'CLRLOW')):
            bad.append('microword %d writes %s and branches on %s, which reads '
                       'the value it is replacing -- %s'
                       % (i, reads, f.get('cond'), c))
        if (f.get('cond') in COND_READS_CCR
                and f.get('ccr', 'NONE') != 'NONE'):
            bad.append('microword %d writes the condition codes and branches on '
                       '%s, which reads them as they stand -- %s'
                       % (i, f.get('cond'), c))
    return bad


# The result bus reaches the next micro-address by exactly two routes: a
# condition that reads the result of its own microword rather than a register,
# and the status register written in the same microword, which `sr_eff` passes
# straight through to the interrupt test at a boundary. From an operand source,
# through the ALU and either route, to the microcode store is the longest
# combinational path in the design, and scripts/paths.tcl cuts it for the deep
# units on the strength of this check: a microword on either route takes its
# result from the ALU alone and from shallow sources, never from the shifter,
# the bit-field unit or the multiplier and divider. doc/critical-path.md.
COND_LIVE = ('RESM1', 'RESNEG', 'GTZ')
DEEP_SOURCES = ('BF_', 'MUL', 'DIV')


def check_live_cond():
    bad = []
    for i, (f, c) in enumerate(program.WORDS):
        if f.get('seq') == 'COND' and f.get('cond') in COND_LIVE:
            why = 'branches on %s, which reads its own result' % f.get('cond')
        elif f.get('dst') == 'SR':
            why = 'writes SR, which the interrupt test reads the same clock'
        else:
            continue
        if f.get('alu') == 'SHIFT':
            bad.append('microword %d %s, and takes the result from the shifter '
                       '-- %s' % (i, why, c))
        for src in ('asrc', 'bsrc'):
            v = f.get(src, '')
            if any(v.startswith(d) for d in DEEP_SOURCES):
                bad.append('microword %d %s, and feeds it from %s -- %s'
                           % (i, why, v, c))
    return bad


# The shifter's operand comes from a data register or from read data and from
# nothing else. Its input multiplexer is the A bus, which can also carry the
# bit-field unit's outputs, and bit-field unit -> shifter -> condition codes is
# the next-longest path once the ones above are gone; scripts/paths.tcl cuts it
# on the strength of this check.
SHIFT_SOURCES = ('DREG', 'RDATA')


def check_shift_src():
    return ['microword %d shifts %s, and the shifter is fed only from %s -- %s'
            % (i, f.get('asrc', 'ZERO'), ' or '.join(SHIFT_SOURCES), c)
            for i, (f, c) in enumerate(program.WORDS)
            if f.get('alu') == 'SHIFT'
            and f.get('asrc', 'ZERO') not in SHIFT_SOURCES]


# The effective-address routines are free to use T2, T3 and XW: absolute long
# assembles its address in T2, the memory-indirect modes need T2 and T3 for the
# base and the intermediate pointer, and the indexed modes decode their
# extension word in XW. So nothing may be held in any of the three across an
# EAMODE call. Until M12 the routines used T0 and T1, while MOVE, the immediate
# instructions, MOVEM, MOVES, CAS, CMP2 and the bit fields held operands in T0
# across the call -- so a memory destination with an absolute long or indexed
# address wrote the wrong thing. Found by booting a Sun-3 PROM on the core,
# which ran MOVES to (xxx).L as a read (doc/bugs-found.md).
#
# A forward scan from every return point: a read of one of the three before a
# write to it, on any path to the end of the instruction, is the bug.
EA_SCRATCH = ('T2', 'T3', 'XW')
XW_SOURCES = ('XW', 'XW_HI', 'DREG_XQ', 'DREG_XR', 'DREG_XU', 'RTM_XW', 'XREG',
              'XWDISP8', 'INDEX')
XW_DESTS = ('XREG', 'XREG_SZ', 'DREG_XR', 'DREG_XQ', 'DREG_XU')


def _ea_reads(f):
    """The EA-scratch registers a microword reads."""
    r = set()
    for fld in ('asrc', 'bsrc'):
        v = f.get(fld, '')
        if v in ('T2', 'T3'):
            r.add(v)
        if v in XW_SOURCES or v.startswith('BF_'):
            r.add('XW')
    if f.get('dst', '') in XW_DESTS:
        r.add('XW')
    if f.get('seq') == 'COND':
        c = COND_READS.get(f.get('cond'))
        if c in EA_SCRATCH:
            r.add(c)
    # The implicit readers, from every use of xw_q and t_q[2], t_q[3] in
    # rtl/rd68021_seq.sv that no source or destination field names: the long
    # multiply and divide take their signedness from the extension word
    # (mdext), the bit fields their offset and width, the static bit
    # instructions their bit number (bitimm), MOVEC its control register; the
    # divider its dividend from T3:T2, and the bit-field unit what it inserts
    # from T3.
    if f.get('mdext') or f.get('bitimm') or f.get('ccr', '') in ('BF', 'BFINS') \
            or f.get('szsel', '') in ('BFREG', 'BFMEM') \
            or 'CREG' in (f.get('asrc', ''), f.get('dst', '')):
        r.add('XW')
    if f.get('mdop', 'NONE') == 'DIV':
        r.update(('T2', 'T3'))
    if f.get('ccr', '') == 'BFINS' or any(
            f.get(k, '').startswith('BF_MERGED') for k in ('asrc', 'bsrc')):
        r.add('T3')
    if f.get('asel', '') in ('T2', 'T3'):
        r.add(f['asel'])
    return r


# --------------------------------------------------------------------------
# Read data does not survive a fault -- except into the read that fetched it
#
# The bus unit's read data is not in the checkpoint set: after a fault and RTE
# it is whatever the last read returned. doc/checkpoint.md rule 2 makes a
# faulted microword re-executable, but only if everything it reads is still what
# it was. A microword can take a fault if it has a bus request (a data fault) or
# uses the pipe (a prefetch fault), and either is re-executed after RTE.
#
# One case is safe, and it is the common one: a bus READ taking the value it is
# itself reading. If that read faults it commits nothing; RTE hands the operand
# back to the bus unit (rstop), which reruns what is left of it -- DF set -- or
# satisfies it from the frame's data input buffer -- DF clear -- and loads the
# read data on the same edge as the acknowledge either way. So the re-executed
# microword sees exactly the data it would have seen. Not if it could also take
# a PREFETCH fault: DF is then clear and the frame's buffer is stale, and RTE
# would satisfy the read from it. check_read_no_pipe keeps reads off the pipe.
#
# Not either for the CPU-space reads whose bus error is an answer and not a
# fault -- the interrupt and breakpoint acknowledges, and the access that starts
# a coprocessor instruction: they complete, and commit, whatever came back.
#
# SunOS found the rule's first form: libc's strcmp loop is CMPM, whose last
# microword compared the read data and advanced the pipe. doc/bugs-found.md.
# --------------------------------------------------------------------------
def reads_rdata(f):
    """The microword reads the bus unit's read data, directly or through a unit
    whose input it is."""
    # A memory bit field is read into a window the bit-field unit works on, so
    # its results, its condition codes and the merged bytes it writes back are
    # all functions of the read data.
    bfmem = f.get('szsel') == 'BFMEM' and (
        any(str(f.get(k, '')).startswith('BF_') for k in ('asrc', 'bsrc'))
        or f.get('ccr') in ('BF', 'BFINS')
        or f.get('bus') == 'WRITE')
    return (f.get('asrc') == 'RDATA' or f.get('bsrc') == 'RDATA'
            or f.get('asrc') == 'IRQVEC' or bfmem)


# The early retire (isa.py `early`): a bus microword retires on the edge that
# ends S5, half a clock after the bus unit has seen the operand finish with no
# bus error and no retry. The read data is latched on that same edge, so a
# microword that takes it cannot retire then; one that does not -- a write, or a
# read whose data the NEXT microword takes -- can. CPU space other than the
# coprocessor's is left alone: an interrupt acknowledge or a breakpoint cycle is
# read by its end code, and the microcode wants the ordinary handshake there.
def mark_early():
    n = 0
    for f, _c in program.WORDS:
        if (f.get('bus') in ('READ', 'WRITE')
                and f.get('cpuspace', 'NONE') in ('NONE', 'COPROC')
                and not any(f.get(k) for k in ('rmc', 'rstop', 'rsto', 'stop'))
                and not reads_rdata(f)):
            f['early'] = 1
            n += 1
    return n


EARLY = None


def uses_pipe(f):
    return (f.get('pf') in ('ADV', 'CONSUME')
            or f.get('asrc') in ('STG_C', 'STG_C_HI', 'PC_C', 'EABASE')
            or f.get('bsrc') in ('STG_C_U', 'STG_C_S')
            or f.get('seq') == 'EADEC')


def check_rdata_restart():
    bad = []
    for i, (f, c) in enumerate(program.WORDS):
        if not reads_rdata(f):
            continue
        bus = f.get('bus', 'NONE')
        effect = f.get('dst', 'NONE') != 'NONE' or f.get('ccr', 'NONE') != 'NONE'
        own_read = (bus == 'READ'
                    and f.get('cpuspace', 'NONE') in ('NONE', 'COPROC')
                    and f.get('mdop', 'NONE') == 'NONE')
        if uses_pipe(f):
            why = 'uses the pipe'
        elif bus == 'NONE' or (bus == 'WRITE' and not effect) or own_read:
            continue
        else:
            why = 'has a bus request that is not a plain read of what it takes'
        bad.append('microword %d takes a value from RDATA and %s, so RTE would '
                   're-run it on stale read data -- %s' % (i, why, c))
    return bad


# A bus READ never uses the pipe. If it did, a prefetch fault on it would leave
# DF clear, and RTE's hand-back would satisfy the read from a stale frame
# buffer without running a cycle -- see check_rdata_restart.
def check_read_no_pipe():
    return ['microword %d is a bus read that also uses the pipe -- %s' % (i, c)
            for i, (f, c) in enumerate(program.WORDS)
            if f.get('bus') == 'READ' and uses_pipe(f)]


# The fast effective-address paths (program.py, FAST_MODES) address through the
# register and leave the EA buffer as the last instruction left it. So from
# every opcode entry, no microword may read EA -- as an operand or as the bus
# address -- before something on the same path has written it or called the
# mode decoder, which writes it.
def check_ea_set():
    W = program.WORDS
    bad = []

    def reads_ea(f):
        return 'EA' in (f.get('asrc'), f.get('bsrc'), f.get('asel'))

    for pat, tgt, mnem in program.PATTERNS:
        stack, seen = [program.entry(tgt)], set()
        while stack:
            j = stack.pop()
            if j in seen or j >= len(W):
                continue
            seen.add(j)
            f, c = W[j]
            if reads_ea(f):
                bad.append('%s (%s) reaches microword %d, which reads EA before '
                           'anything has set it -- %s' % (mnem, pat, j, c))
                break
            if f.get('dst') == 'EA' or f.get('seq') == 'EAMODE':
                continue
            seq = f.get('seq', 'NEXT')
            if seq in ('DECODE', 'RESUME', 'RET', 'EADEC', 'CPDEC'):
                continue
            nxt = f.get('next')
            tgt_j = program.entry(nxt) if isinstance(nxt, str) else \
                (nxt if nxt is not None else j + 1)
            if seq == 'COND':
                stack += [j + 1, tgt_j]
            elif f.get('call'):
                stack += [tgt_j, j + 1]
            else:
                stack.append(tgt_j)
    return bad


def check_ea_live():
    W = program.WORDS
    bad = []

    def succ(i):
        f = W[i][0]
        seq = f.get('seq', 'NEXT')
        if seq in ('DECODE', 'RESUME', 'RET', 'EADEC'):
            return []
        nxt = f.get('next')
        tgt = program.entry(nxt) if isinstance(nxt, str) else \
            (nxt if nxt is not None else i + 1)
        if seq == 'COND':
            return [i + 1, tgt]
        if seq == 'EAMODE' or f.get('call'):
            return [i + 1]           # the callee returns here
        return [tgt]

    for i, (f, c) in enumerate(W):
        if f.get('seq') != 'EAMODE':
            continue
        # (word, still-live set) pairs; a register is live until written.
        stack = [(i + 1, frozenset(EA_SCRATCH))]
        seen = set()
        while stack:
            j, live = stack.pop()
            if (j, live) in seen or j >= len(W) or not live:
                continue
            seen.add((j, live))
            g = W[j][0]
            hit = _ea_reads(g) & live
            if hit:
                bad.append('microword %d reads %s, which the effective-address '
                           'routine called at microword %d may have overwritten '
                           '-- %s' % (j, '/'.join(sorted(hit)), i, W[j][1]))
                continue
            d = g.get('dst', '')
            if d in EA_SCRATCH:
                live = live - {d}
            if g.get('seq') == 'EAMODE':
                continue             # a second call: scanned from its own return
            for k in succ(j):
                stack.append((k, live))
    return bad


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--check', action='store_true',
                    help='fail if the checked-in files are stale')
    args = ap.parse_args()

    global EARLY
    EARLY = mark_early()

    bad = (frames.check() + isa.check() + check_cond_dst() + check_live_cond() + check_shift_src()
           + check_ea_live() + check_ea_set() + check_rdata_restart() + check_read_no_pipe()
           + check_areg_size() + check_restore_order())
    if bad:
        print('FAIL: the tables are not self-consistent')
        for b in bad:
            print('  %s' % b)
        return 1

    # And against the RTL. doc/checkpoint.md rule 3 -- every register an
    # instruction accumulates has a home in the frame or it does not exist -- is
    # about REGISTERS, so it is checked against the registers rather than
    # against the microcode's destinations. The old check read the destinations
    # and could not see link_q, eapc_q, size_q, eadst_q or cnt_q, all of which
    # are per-instruction state and all of which got past it.
    bad = frames.check_rtl(os.path.join(ROOT, 'rtl'))
    if bad:
        print('FAIL: the checkpoint set does not account for the RTL')
        for b in bad:
            print('  %s' % b)
        return 1

    stale = []
    for path, fn in sorted(OUTPUTS.items()):
        text = fn()
        if args.check:
            if not os.path.exists(path):
                if path.startswith(os.path.join(ROOT, 'build')):
                    continue          # build/ is not committed
                stale.append(path)
            elif open(path).read() != text:
                stale.append(path)
        else:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            with open(path, 'w') as fh:
                fh.write(text)

    if args.check:
        if stale:
            print('FAIL: %d generated file(s) are stale -- run `make ucode`:'
                  % len(stale))
            for p in stale:
                print('  %s' % os.path.relpath(p, ROOT))
            return 1
        have, use, spare = frames.budget()
        print('  ucode-check: %d microwords, %d opcode patterns, %d of %d '
              'checkpoint bits used, %d registers accounted for, %d pending'
              % (len(program.WORDS), len(program.PATTERNS), use, have,
                 sum(len(v) for v in
                     frames.rtl_registers(os.path.join(ROOT, 'rtl')).values()),
                 len(frames.PENDING)))
    else:
        have, use, spare = frames.budget()
        _lay, uww = isa.layout()
        print('  ucode: %d files; %d microwords of %d bits (%d retire early), '
              '%d opcode patterns, %d of %d checkpoint bits used, %d words spare'
              % (len(OUTPUTS), len(program.WORDS), uww, EARLY,
                 len(program.PATTERNS), use, have, len(spare)))
    return 0


if __name__ == '__main__':
    sys.exit(main())
