#!/usr/bin/env python3
"""Generate rtl/gen/ from the tables in this directory, and refuse to if they
are wrong.

    python3 tools/ucode/assemble.py            # regenerate
    python3 tools/ucode/assemble.py --check    # fail if what is checked in is stale

The generated files are committed, so a build needs no Python. `make ucode-check`
is the first thing `make check` runs, so they cannot drift from their source.

The generator is also the design-rule checker. Some properties cannot be stated in
RTL -- that no two checkpointed registers share a bit of the fault frame, that the
short frame carries no private state, that every frame is exactly as long as the
manual says -- so they are stated here and fail the build instead.

As of M4 this emits the frame package. The microword, the decoders and the
microcode store arrive in M5.
"""

import argparse
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
GEN = os.path.join(ROOT, 'rtl', 'gen')
sys.path.insert(0, HERE)

import frames                                                   # noqa: E402

BANNER = """// RD68021 - SystemVerilog MC68020
//
// GENERATED by tools/ucode/assemble.py from tools/ucode/frames.py. Do not edit:
// `make ucode-check` compares this file against its source and fails the build if
// they have drifted.
//
"""


def frame_pkg():
    out = [BANNER]
    out.append("""// The six exception stack frames -- UM Table 6-5 -- and the offsets this design
// keeps its own state at inside the long one.
//
// One wrong offset here is a silent demand-paging failure: the frame would be
// written correctly enough to pass its own format check and read back one word
// out. tools/ucode/frames.py is the single place any of these numbers exists.

`ifndef RD68021_FRAME_PKG_SV
`define RD68021_FRAME_PKG_SV

package rd68021_frame_pkg;

  // ==========================================================================
  // Frame sizes, in bytes, as the stack pointer must be adjusted by
  // ==========================================================================""")
    for fmt in sorted(frames.FRAMES):
        f = frames.FRAMES[fmt]
        out.append('  localparam int FRAME_%X_BYTES = %d;   // %s, %d words'
                   % (fmt, 2 * f['words'], f['name'], f['words']))

    out.append("""
  // ==========================================================================
  // Architecturally named fields -- UM Table 6-5
  //
  // OFF is the byte offset from the stack pointer; a field present in more than
  // one frame is at the same offset in each, which is what makes one set of
  // constants right for all of them.
  // ==========================================================================""")
    seen = {}
    for fmt in sorted(frames.FRAMES):
        for off, n, field in frames.FRAMES[fmt]['slots']:
            if field in ('internal', 'version'):
                continue
            if field in seen:
                if seen[field] != (off, n):
                    raise SystemExit('assemble: field %r is at +$%02X in one frame '
                                     'and +$%02X in another -- the generator assumes '
                                     'it is not' % (field, seen[field][0], off))
                continue
            seen[field] = (off, n)
            out.append('  localparam int OFF_%-13s = \'h%02X;   // %d word%s, %s'
                       % (field.upper(), off, n, '' if n == 1 else 's',
                          frames.ARCH_FIELDS[field]))

    out.append("""
  // ==========================================================================
  // The version number -- UM 6.1.12
  //
  // "The version number is located in the most significant nibble (bits 15-12)
  // of the word at location SP + $36 in the long stack frame." RTE compares it
  // with its own and takes a format error if they differ, which is the contract
  // that makes this design's private encoding of the internal words legitimate.
  // It is also why the SHORT frame, which has no version field, carries none of
  // them. See doc/manual-contradictions.md for why the offset is $36.
  // ==========================================================================""")
    out.append('  localparam int         OFF_VERSION  = \'h%02X;' % frames.VERSION_OFFSET)
    out.append('  localparam int         VERSION_HI   = %d;' % frames.VERSION_HI)
    out.append('  localparam int         VERSION_LO   = %d;' % frames.VERSION_LO)
    out.append('  localparam logic [3:0] FRAME_VERSION = 4\'h%X;' % frames.VERSION)

    have, use, spare = frames.budget()
    out.append("""
  // ==========================================================================
  // This design's own state, in the long frame's internal words
  //
  // %d bits available, %d used, %d words spare. Recompute this whenever
  // something is added: doc/checkpoint.md carries the same table, printed from
  // the same source.
  // ==========================================================================""" % (have, use, len(spare)))
    for off, hi, lo, name, bits, what in frames.INTERNAL:
        out.append('  localparam int OFF_%-11s = \'h%02X;   // %2d bits, %s'
                   % ('I_' + name.upper(), off, bits, what))
        out.append('  localparam int %-15s = %d;'
                   % ('I_' + name.upper() + '_HI', hi))
        out.append('  localparam int %-15s = %d;'
                   % ('I_' + name.upper() + '_LO', lo))

    out.append("""
endpackage

`endif""")
    return '\n'.join(out) + '\n'


def doc_tables():
    """The tables doc/checkpoint.md carries, printed from the same source."""
    out = []
    out.append('### The frames\n')
    out.append('| Format | Words | Name | Layout |')
    out.append('|---|--:|---|---|')
    for fmt in sorted(frames.FRAMES):
        f = frames.FRAMES[fmt]
        bits = []
        for off, n, field in f['slots']:
            label = field if field != 'internal' else 'internal'
            bits.append('`+$%02X` %s%s' % (off, label,
                                           '' if n == 1 else ' ×%d' % n))
        out.append('| `$%X` | %d | %s | %s |'
                   % (fmt, f['words'], f['name'], ', '.join(bits)))

    out.append('\n### The private words of the long frame\n')
    out.append('| Offset | Bits | Register | What |')
    out.append('|---|---|---|---|')
    for off, hi, lo, name, bits, what in frames.INTERNAL:
        r = '%d' % hi if hi == lo else '%d:%d' % (hi, lo)
        out.append('| `+$%02X` | %s | `%s` | %s |' % (off, r, name, what))
    have, use, spare = frames.budget()
    out.append('\n**%d bits available, %d used, %d words spare** (%s).'
               % (have, use, len(spare),
                  ', '.join('`+$%02X`' % w for w in spare)))

    out.append('\n### The frozen set\n')
    out.append('| Unit | Register | Bits | Lands in | |')
    out.append('|---|---|--:|---|---|')
    for unit, reg, bits, slot, note in frames.CHECKPOINT:
        out.append('| `%s` | `%s` | %d | `%s` | %s |' % (unit, reg, bits, slot, note))

    out.append('\n### Not checkpointed, and why\n')
    out.append('| | |')
    out.append('|---|---|')
    for what, why in frames.NOT_CHECKPOINTED:
        out.append('| %s | %s |' % (what, why))
    return '\n'.join(out) + '\n'


OUTPUTS = {
    os.path.join(GEN, 'rd68021_frame_pkg.sv'): frame_pkg,
    os.path.join(ROOT, 'build', 'checkpoint-tables.md'): doc_tables,
}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--check', action='store_true',
                    help='fail if the checked-in files are stale')
    args = ap.parse_args()

    bad = frames.check()
    if bad:
        print('FAIL: the frame table is not self-consistent')
        for b in bad:
            print('  %s' % b)
        return 1

    stale = []
    for path, fn in sorted(OUTPUTS.items()):
        text = fn()
        if args.check:
            if not os.path.exists(path):
                if path.startswith(os.path.join(ROOT, 'build')):
                    continue          # build/ is not committed
                stale.append(path)
            elif open(path).read() != text:
                stale.append(path)
        else:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            with open(path, 'w') as fh:
                fh.write(text)

    if args.check:
        if stale:
            print('FAIL: %d generated file(s) are stale -- run `make ucode`:'
                  % len(stale))
            for p in stale:
                print('  %s' % os.path.relpath(p, ROOT))
            return 1
        have, use, spare = frames.budget()
        print('  ucode-check: frames consistent, %d of %d checkpoint bits used, '
              '%d words spare' % (use, have, len(spare)))
    else:
        have, use, spare = frames.budget()
        print('  ucode: %d generated file(s); %d of %d checkpoint bits used, '
              '%d words spare' % (len(OUTPUTS), use, have, len(spare)))
    return 0


if __name__ == '__main__':
    sys.exit(main())
